windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = gaming-perf
    match:workspace = 4

    opacity = 1.0 1.0
    no_blur = on
}

windowrule = workspace 2 silent, match:class zen-browser
windowrule = workspace 3, match:class zed
windowrule = workspace 3, match:class kitty
windowrule = workspace 4, match:class steam
windowrule = workspace 4 silent, match:class spotify-launcher

# ── Layer Rules ──
layerrule = animation slide, match:namespace swaync
layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 2, match:namespace wofi
# layerrule = noanim, ^(volume_osd)$        # uncomment if you add swayosd later
# layerrule = noanim, ^(brightness_osd)$    # same
# layerrule = noanim, hyprpicker            # uncomment if you install hyprpicker
# layerrule = blur, ext-session-lock        # uncomment when hyprlock is set up
# layerrule = ignorealpha 0.2, ext-session-lock  # same

# ── QS App Launcher (uncomment when Quickshell launcher is built) ──
# windowrulev2 = float, title:^(app-launcher)$
# windowrulev2 = center, title:^(app-launcher)$
# windowrulev2 = size 1200 600, title:^(app-launcher)$
# windowrulev2 = animation slide, title:^(app-launcher)$

# ── QS Master container (uncomment when full Quickshell stack is ported) ──
windowrule{
    name = qs-master
    match:initial_title = ^(qs-master)$
    match:initial_class = ^(org.quickshell)$

    no_initial_focus = true
    pin = true
    float = true
    no_blur = true
    no_shadow = true
    border_size = 0
    move = -5000 -5000
    }
