exec-once = kitty
exec-once = zeditor
exec-once = awww-daemon
exec-once = wofi --no-actions
exec-once = steam -silent
exec-once = vesktop -silent
exec-once = spotify-launcher
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#cursor
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'dracula-cursors-git'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

exec-once = awww img -o DP-1 ~/Pictures/Wallpapers/main.png
exec-once = awww img -o HDMI-A-1 ~/Pictures/Wallpapers/2ndary.png

exec-once = quickshell -p ~/.config/quickshell/TopBar.qml

exec-once = easyeffects --gapplication-service
